### ISSUE TITLE
ViewBridge decorator?

### ISSUE THREAD

**Issue by benlesh** [Brocco/ng-bridge#1]
So looking at your examples, the only thing that's obvious to me is that the `ComponentBridge` decorator is _one_ decorator, while `Component` and `View` from ng2 are _two_ decorators.

I'd advise splitting those to have the `template` in a `ViewBridge` decorator.

---

In your examples, I would then show you importing and aliasing the `*Bridge` decorators to have the same name as ng2 gives them in the modules....

``` TypeScript
import { ComponentBridge as Component, ViewBridge as View } from 'ng-bridge';

@Component({
    selector: 'person',
    properties: ['firstName', 'lastName'],
    controllerAs: 'p'
})
@View({
    template: `<div>{{p.firstName}} {{p.lastName}}</div>`
})
export default class Person {
  /* stuff */
}
```

---

then when a user needs to upgrade to ng2, they just need to change their `import` and their template (in theory and at a minimum)

**Comment by Brocco** [comment]
@blesh I just pushed a branch with code that should handle this (had to move a few things around) please take a look. I still have to update the README to reflect the changes as well as test via the corresponding samples repo.

**Comment by benlesh** [comment]
Which branch?

**Comment by Brocco** [comment]
Sorry, should have been more clear... 

view-bridge is the name of the branch, you can find the commit here: https://github.com/Brocco/ng-bridge/commit/bd461a5aca4e36bd205ee43c927462ee5fda663c

**Comment by Brocco** [comment]
Closed as the code has been merged in (should've done a pull request, but I am new to github's issue/commit tracking.
